export const SIGN_IN = 'SIGN_IN'
export const USER_INFO = 'USER_INFO'

export const PROFESSIONS_LIST = 'PROFESSIONS_LIST'
export const REGIONS_LIST = 'REGIONS_LIST'
export const TYPE_ORGAN_LIST = 'TYPE_ORGAN_LIST'
export const SEARCH_LIST = 'SEARCH_LIST'
export const SEARCH_HISTORY = 'SEARCH_HISTORY'
export const DRIVER_LICENSE_LIST = 'DRIVER_LICENSE_LIST'
export const CURRENCY_LIST = 'CURRENCY_LIST'
export const SPECIALITY_LIST = 'SPECIALITY_LIST'
export const LANGUAGE = 'LANGUAGE'
export const FEEDBACK = 'FEEDBACK'
export const FEEDBACK_CREATE = 'FEEDBACK_CREATE'

export const EMPLOYER_LIST = 'EMPLOYER_LIST'
export const EMPLOYER_ITEM = 'EMPLOYER_ITEM'

export const SLIDER_LIST = 'SLIDER_LIST'

export const APPLICANT_LIST = 'APPLICANT_LIST'
export const APPLICANT_ITEM = 'APPLICANT_ITEM'
export const APPLICANT_UPDATE = 'APPLICANT_UPDATE'
export const APPLICANT_FAV_VACANCY_LIST = 'APPLICANT_FAV_VACANCY_LIST'

export const VACANCY_LIST = 'VACANCY_LIST'
export const VACANCY_ITEM = 'VACANCY_ITEM'
export const VACANCY_POPULAR_LIST = 'VACANCY_POPULAR_LIST'
export const VACANCY_APPEALED_LIST = 'VACANCY_APPEALED_LIST'

export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const ASYNC_LOADING = 'ASYNC_LOADING'

export const RESUME_DEACTIVATE = 'RESUME_DEACTIVATE'
export const RESUME_ACTIVATE = 'RESUME_ACTIVATE'

export const RESUME_ACTIVE_LIST = 'RESUME_ACTIVE_LIST'
export const RESUME_ACTIVE_ITEM = 'RESUME_ACTIVE_ITEM'
export const RESUME_ITEM_UPDATE_DATE = 'RESUME_ITEM_UPDATE_DATE'
export const RESUME_LIST = 'RESUME_LIST'
export const RESUME_CREATE = 'RESUME_CREATE'
export const RESUME_UPDATE = 'RESUME_UPDATE'
export const RESUME_ITEM = 'RESUME_ITEM'
export const RESUME_ITEM_GUESTS = 'RESUME_ITEM_GUESTS'

export const PERFORMER_LIST = 'PERFORMER_LIST'
export const PERFORMER_ITEM = 'PERFORMER_ITEM'
export const PERFORMER_UPDATE = 'PERFORMER_UPDATE'

export const CLIENT_LIST = 'CLIENT_LIST'
export const CLIENT_ITEM = 'CLIENT_ITEM'
export const CLIENT_UPDATE = 'CLIENT_UPDATE'

export const TASK_LIST = 'TASKT_LIST'
export const TASK_ITEM = 'TASKT_ITEM'
export const TASK_UPDATE = 'TASKT_UPDATE'
export const TASK_CREATE = 'TASK_CREATE'

export const DOCUMENTS_LIST = 'DOCUMENTS_LIST'
export const DOCUMENTS_ITEM = 'DOCUMENTS_ITEM'
export const DOCUMENTS_UPDATE = 'DOCUMENTS_UPDATE'
export const DOCUMENTS_CREATE = 'DOCUMENTS_CREATE'

export const REESTR_LIST = 'REESTR_LIST'
export const REESTR_ITEM = 'REESTR_ITEM'

export const CATEGORY_LIST = 'CATEGORY_LIST'
export const CATEGORY_ITEM = 'CATEGORY_ITEM'
export const CATEGORY_UPDATE = 'DOCUMENTS_UPDATE'
export const CATEGORY_CREATE = 'DOCUMENTS_CREATE'

export const NEWS_LIST = 'NEWS_LIST'
export const NEWS_ITEM = 'NEWS_ITEM'
export const NEWS_UPDATE = 'NEWS_UPDATE'
export const NEWS_CREATE = 'NEWS_CREATE'

export const SYSTEM_PAGES = 'SYSTEM_PAGES'

export const RUKOVODITELI_LIST = 'RUKOVODITELI_LIST'
export const RUKOVODITELI_ITEM = 'RUKOVODITELI_ITEM'
